source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

workspace 'ObjCSDKVerification'
target 'ObjCSDKVerification' do
  pod 'ampiri-ios-sdk/Adapters/AdColonyAdapter'
  pod 'ampiri-ios-sdk/Adapters/GoogleMobileAdsAdapter'
  pod 'ampiri-ios-sdk/Adapters/AppLovinAdapter'
  pod 'ampiri-ios-sdk/Adapters/ChartboostAdapter'
  pod 'ampiri-ios-sdk/Adapters/FBAudienceAdapter'
  pod 'ampiri-ios-sdk/Adapters/MopubAdapter'
  pod 'ampiri-ios-sdk/Adapters/NativeXAdapter'
  pod 'ampiri-ios-sdk/Adapters/UnityAdsAdapter'
  pod 'ampiri-ios-sdk/Adapters/VungleAdapter'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
